### ISSUE TITLE
Please add logging example for uuid-Telnet uuid-console 

### ISSUE THREAD

**Issue by SpaceTeddy** [nomis/mcu-uuid-log#1]
Dear all,
Thanks a lot for these amazing set of uuid tools. 
basically I use the uuid console and would like to use the telnet console also for debugging. 
in your example, only Serial logging example is provided, which works fine, burnside have trouble to use it with the running telnet console.
May you help with an example? 

Thx
Chris

**Comment by nomis** [comment]
The Shell in uuid-console is a log handler with a default level of NOTICE: https://github.com/nomis/mcu-uuid-console/blob/3.0.1/src/shell.cpp#L54-L55

You can add commands to configure a different log level: https://mcu-doxygen.uuid.uk/classuuid_1_1console_1_1Shell.html#ae47bd94c87f13242799bdde67e2f77ed

**Comment by SpaceTeddy** [comment]
Wow, thanks a lot for your hyper speed feedback 👍. 
my basic problem in my project is, that I can not use the shell.printf function over different cpp files. Only in my command.cpp where all my commands and functions are defined. If I try to define it globally in commands.h with extern uuid::…. I get linker problems with platforms and esp32.
Do you have an good advice how to implement shell.printf global?

thanks again 
Chris

**Comment by nomis** [comment]
You can pass Shell as a reference to other functions from your command functions: https://github.com/nomis/mcu-app/blob/f57fa1ca73e82496ea3474b4cdaa71729f19e565/src/network.cpp#L259

It's not designed to have printf called from outside a command, the logging functions are intended to provide that.

**Comment by nomis** [comment]
I've added some documentation for this here: https://github.com/nomis/mcu-uuid-console/commit/2897fd4b68dd4d42e931cdb9c67b449fcd2752dd

**Comment by SpaceTeddy** [comment]
Alright nomis,
I will take a look to your documentation update. 
Thanks a lot for your time and I will feedback if this helps for my project :)

thanks again
Chris

**Comment by SpaceTeddy** [comment]
Dear Simon,
I tried with your two examples of telnet console and example of Seriallogging handler to get global logging via telnet output but unfortunately I failed 😞.
Probably of lack of good C++ skills 🫣.

unfortunatly I would like to ask again for some more detailed hints to activate the global logger for telnet output. Maybe there is just a stream change needed, but not sure where and how to do this.

btw: also some other features I could not find out how to do. a) customized display_banner() or welcome screen and  b) use Hostname instead of console „$“.

🫣😇😞

sers, 
Chris

**Comment by SpaceTeddy** [comment]
Dear Simon,
Sry to ask again for some hints to activate the logging in the telnet console.  Currently I use your syslog logging, but this is a bit oversized for my project:)
So, it would be really nice to have the telnet console logging running.
Hope you can find some time to give me some hints. 
thx
Chris

**Comment by nomis** [comment]
> unfortunatly I would like to ask again for some more detailed hints to activate the global logger for telnet output. Maybe there is just a stream change needed, but not sure where and how to do this.

I'd need to see your code to understand why you're not getting log messages. If the syslog service is working then the shell should be getting the log messages too.

> btw: also some other features I could not find out how to do. a) customized display_banner() or welcome screen and b) use Hostname instead of console „$“.

I don't have a simple working example for this. Create your own class that extends `uuid::console::Shell`. When you construct the `uuid::telnet::TelnetService`, pass a lambda function to the constructor that returns a new instance of your class and overrides those functions:
```
class MyShell: public uuid::console::Shell {
...
protected:
	void display_banner() override;
	std::string hostname_text() override;
};

[this] (Stream &stream, const IPAddress &addr, uint16_t port) -> std::shared_ptr<uuid::console::Shell> {
    return std::make_shared<MyShell>(stream, commands);
}
```

**Comment by SpaceTeddy** [comment]
Dear Simon,
this is a stripped version of my code. 
I didn't compiled this version ,but it has the basic information included. my commands are in command.h & command.cpp

```cpp
#include <Arduino.h>

#include <memory>
#include <string>
#include <vector>

#include <uuid/common.h>
#include <uuid/console.h>
#include <uuid/telnet.h>
#include <uuid/syslog.h>
#include "commands.h"

using uuid::read_flash_string;
using uuid::flash_string_vector;
using uuid::console::Commands;
using uuid::console::Shell;

// uuid-console + telnet
static std::shared_ptr<uuid::console::Commands> commands = std::make_shared<uuid::console::Commands>();
static uuid::telnet::TelnetService telnet{commands};

//uuid-syslog
static uuid::syslog::SyslogService syslog;

setup(){
    //Setup Console
    registerCommands(commands);
    telnet.start();

    //Setup syslog
    //Setup Logger
    static uuid::log::Logger logger{F("setup")};

    syslog.start();
    String hostname_syslog = hostname_base + get_flashmemory_id();
    syslog.hostname(hostname_syslog.c_str());
    syslog.log_level(uuid::log::ALL);
    syslog.mark_interval(3600);
    syslog.destination(IPAddress(192, 168, 0, 207), 514);

    // Log testmessage
    logger.info(F("LLU Client Application started"));
}

loop(){

    uuid::loop();
    syslog.loop();
    telnet.loop();
    Shell::loop_all();yield();

}
```

command.h
```cpp
#pragma once
#include <memory>
#include <string>
#include <vector>

#include <uuid/common.h>
#include <uuid/console.h>
#include <uuid/telnet.h>
#include <uuid/console.h>


void registerCommands(std::shared_ptr<uuid::console::Commands> commands);

int parseArgument(const std::vector<std::string> &arguments, size_t index, int defaultValue);

```

commands.cpp
```cpp
#include "commands.h"

int parseArgument(const std::vector<std::string> &arguments, size_t index, int defaultValue = 0) {
    if (index < arguments.size()) {
        return std::stoi(arguments[index]);
    }
    return defaultValue;
}

void helpCommand(uuid::console::Shell &shell, const std::vector<std::string> &) {
    shell.printfln(F("Available commands:"));
    shell.print_all_available_commands(); 
}

void espResetCommand(uuid::console::Shell &shell, const std::vector<std::string> &) {
    shell.printfln(F("ESP Reset!"));
    ESP.restart();
}

void registerCommands(std::shared_ptr<uuid::console::Commands> commands) {
    commands->add_command(uuid::flash_string_vector{F("help")}, helpCommand);
    commands->add_command(uuid::flash_string_vector{F("esp_reset")}, espResetCommand);
}

```

**Comment by SpaceTeddy** [comment]
In addition I added a GitHub repo for my basic stripped code.
https://github.com/SpaceTeddy/uuid-console-log-telnet-test.git
I did not test this on a target, but the uuid functions are the same as on my full project.

thanks in advance 
Chris

**Comment by nomis** [comment]
You won't get log messages in your shell that happened before you connected, and the default log level of the shell is NOTICE, which is higher than INFO so your log messages will be filtered out.

Add a command to change the log level of the current shell.

**Comment by SpaceTeddy** [comment]
Dear Simon,
alright good to know. Most likely I missed that, that I have to change the log level first.
alter set the level to ALL, I can see the messages. 
```cpp
void setLoglevelCommand(uuid::console::Shell &shell, const std::vector<std::string> &) {
    shell.printfln(F("Set Loglevel to ALL:"));
    shell.log_level(uuid::log::Level::ALL);
}
```
````
000+00:05:03.842 I 542: [main] test
000+00:05:03.842 D 543: [main] test
000+00:05:04.846 I 544: [main] test
000+00:05:04.846 D 545: [main] test
000+00:05:05.848 I 546: [main] test
000+00:05:05.848 D 547: [main] test
$ 
Connection closed by foreign host.
```
Thanks a lot for your help and hints! ;)

sers,
Chris
